blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/mkkhedawat/rest.ground/discussions/categories/ideas
    about: Search and submit ideas for this project
